# Generated by Django 2.1.7 on 2019-05-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='no_name', max_length=50),
            preserve_default=False,
        ),
    ]
